---

- name: Ensure latest nginx and supporting packages are installed
  become: yes
  apt:
    pkg: nginx
    state: present

- name: Ensure includes folder exists
  become: yes
  file:
    name: /etc/nginx/includes
    owner: root
    group: root
    state: directory
